### ISSUE TITLE
Experiment Transport layer with java-coap (fork)

### ISSUE THREAD

**Issue by sbernard31** [eclipse-leshan/leshan#1373]
To test new transport layer (#1025),  we decide to experiment it a little with : [**java-coap (fork)**](https://github.com/open-coap/java-coap). (see : https://github.com/eclipse/leshan/issues/1338)

This issue aims to centralize discussion about it.

**Comment by sbernard31** [comment]
@JaroslawLegierski I know you started to work about it, do you have any code to share.

You are working on client side right ?

**Comment by JaroslawLegierski** [comment]
> You are working on client side right ?

Yes I have first version. I am currently able to perform registration, reg update, send data to server and deregister client. 
The code doesn't look good (it's a terrible mess) - so I'd like to clean it a bit before sharing.

**Comment by sbernard31** [comment]
@JaroslawLegierski do not hesitate to share even if code is not so good.

On my side, I will also begin to work on this as I'm a bit stuck : 
- integrating transport layer abstraction : waiting for feedback from orange.
- refactor transport Layer Module following #1295 : try to get some feedback ?
- exploring coap+tcp  :  waiting for feedback from californium to move forward.

As you are on client, I will try to look at server side :thinking:

**Comment by JaroslawLegierski** [comment]
OK the code won't be fully cleaned but I'd like to at least remove all failed "test blocks" from it. Unfortunately, I spend a some time on organizational tasks lately (e.g. point 1 from the list above ;-) and generally I'm a little late in this week.

**Comment by sbernard31** [comment]
(take your time, no pressure :wink:)

**Comment by sbernard31** [comment]
I started to code something in [`java-coap`](https://github.com/eclipse/leshan/compare/java-coap) branch.
This is not clean at all (very inspired from what I did with californium which is maybe not a good idea ? :thinking: )
This is not tested (not ever run) but I share it just in case it could helps. => https://github.com/eclipse/leshan/commit/a45f3108c05792c2c5b781591182165b1fd3b407

**Comment by JaroslawLegierski** [comment]
Please find my first tests results [here]( https://github.com/JaroslawLegierski/leshan/tree/opl/endpoint_client_javacoap) . I started by modifying the existing cf-handling classes. It seems to me that Your approach (starting from the scratch) is definitely better because I'm still using cf classes and I still have a mess in the code.

**Comment by JaroslawLegierski** [comment]
Please find [here](https://github.com/eclipse/leshan/commit/7f48980b5e43d2e70759ff2f1fc92d11d5c9ff2a) new very initial version of leshan client using java-coap. This version has been developed based on template from you and should (finally) no longer contain the californium code.  Thanks for your help and pointing me in the right direction ;-).

**Comment by sbernard31** [comment]
@JaroslawLegierski do not hesitate to share if you find anything smelly in new transport layer abstraction.

On my side, I moved forward about implementing Endpoints provider for server based on `java-coap`. 
This is still available in [`java-coap`](https://github.com/eclipse/leshan/commits/java-coap) branch. (commit 5b0b66fa675da2ad9224d15e828036d0c06d0f40)
For now, I'm only focus on coap (not coaps).

I inspired myself from your work (translator + request/response builder).

Currently, I'm able to do : 
 - :heavy_check_mark:  **register** /  **update**/ **deregister** 
 - :heavy_check_mark:  also send **Read** / **Write** / **Execute** / **Create** request.

What is not implemented : 
- :x:  **observe** I didn't look at java-coap api about that for now. (this will probably the painful part .... observe is always the painful part...)
- :x: **send** is not implemented (this should be not so hard to implement)
- :x:  All **composite Operations** because java-coap doesn't support Fetch and IPatch.

There is also some TODO which I need investigate, this will probably lead to some discussion with `java-coap `maintainer. 

Next step ?
 - maybe adding a way to have several endpoints provider this ways I could have java-coap and californium at the same time.
 - probably trying to redesign tests to be able to execute it with different endpoint providers. (this way not need to rewrite all tests)

**Comment by JaroslawLegierski** [comment]
In my last version [client](https://github.com/JaroslawLegierski/leshan/tree/opl/endpoint_client_tl_javacoap) I implemented initial version of Read function.  I took the ResponseCodeUtil class from you :smile:. Some variables are still hardcoded but I will try clean it in new versions e.g. ServerIdentity (needed by ReadResponse in ObjectResource). In cf ServerIdentity  was available in CoapExchange I don't know if there is something similar in java-coap api.

**Comment by sbernard31** [comment]
> In my last version [client](https://github.com/JaroslawLegierski/leshan/tree/opl/endpoint_client_tl_javacoap) I implemented initial version of Read function.

:+1:  I will look at this next week.

> In cf ServerIdentity was available in CoapExchange I don't know if there is something similar in java-coap api.

Yep this is something we will need to ask especially for coap over dtls

As for now we just test with coap, I create identity like this : `return Identity.unsecure(coapRequest.getPeerAddress());` See in `LwM2mCoapResource.getForeignPeerIdentity(CoapRequest coapRequest)` (in my branch)

**Comment by sbernard31** [comment]
I moved a bit forward.
This is still available in [java-coap](https://github.com/eclipse/leshan/commits/java-coap) branch.

I added support of  : 
- :heavy_check_mark: **send** operation was not so hard.  (commit 21134c62be6732ba2055ea355b406278a8d56462)
- :heavy_check_mark: **observe** was a bit complicated and we do not persist observe relation (See https://github.com/open-coap/java-coap/issues/27#issuecomment-1385782372 for more details). (commit 4c1913b694406ccb90089c3f449f018d951e6390, 475baf7d97f4e737321de739e3b81131b6134a3c)

_(Note this is still a draft, that means a lot of polish/tests are missing)_

**Comment by sbernard31** [comment]
> Could you make it a draft PR? It would be easier to write comments or ask questions.

Yep, this is done #1382.

**Comment by JaroslawLegierski** [comment]
From my side, only small progress in [3d49df0](https://github.com/JaroslawLegierski/leshan/commit/3d49df0c85dd86817e03ffd4020ab3c623dbadea) - mainly I found and corrected some bugs in the read function and added send. I also used Your random token generator.

**Comment by sbernard31** [comment]
I finally finished to modify our integration tests to be able to test different transport (See #1425)

I will be able to move forward on this again.

**Comment by JaroslawLegierski** [comment]
Unfortunately I didnt you move forward on the client from last time :worried:. Because currently most important for us is #1421 topic please feel free to reuse  my [java-coap work ](https://github.com/JaroslawLegierski/leshan/tree/opl/endpoint_client_tl_javacoap)

**Comment by sbernard31** [comment]
> Unfortunately I didnt you move forward on the client from last time.

@JaroslawLegierski no problem. :slightly_smiling_face: 

> please feel free to reuse my java-coap work 

Thx :pray: 

> Because currently most important for us is #1421 topic

Let's talk about  #1421 in the corresponding issue.

**Comment by sbernard31** [comment]
I move a bit forward about Client side support : https://github.com/eclipse/leshan/pull/1443

**Comment by sbernard31** [comment]
There is now first implementation of CoAP protocol based on **java-coap(fork)** in `master` : 
- https://github.com/eclipse-leshan/leshan/pull/1382#issuecomment-1770499183
- https://github.com/eclipse-leshan/leshan/pull/1443#issuecomment-1771296577

The main purpose was to test transport layer abstraction and I think this is done now, so I will close this issue.

But there is probably more work to do to make it fully production ready.
