### ISSUE TITLE
Why are Github security advisors not used?

### ISSUE THREAD

**Issue by Warmek** [eclipse-leshan/leshan#1439]
### Question

I can see here: https://github.com/eclipse/leshan/security/policy that Github security advisors are not used. Why is that?

**Comment by sbernard31** [comment]
It sounds not possible if when we are under Eclipse Github Organization, see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/449 for more details.

Note that maybe it would be possible by moving Leshan under a dedicated organization : https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1705

**Comment by Warmek** [comment]
What benefits would the use of security advisors bring for Leshan?

**Comment by sbernard31** [comment]
Mainly : 
> You can use repository security advisories to privately discuss, fix, and publish information about security vulnerabilities in your repository.
(source : https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/about-repository-security-advisories)

**Comment by sbernard31** [comment]
Eclipse IT Team ask us if we want to move to our own organization that way we will be able to enable GitHub security advisories for Leshan : https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/449#note_1115464

@Warmek, @jvermillard, @JaroslawLegierski  any opinion about this ?

**Comment by sbernard31** [comment]
Regarding [answers provided by Eclipse Team](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/449#note_1141465).
I plan to ask us to move Leshan in its own organization to have access to GitHub security advisories.

I will probably give them the green light next week.
So @Warmek, @jvermillard, @JaroslawLegierski, you have until the end of the week : 
 - to let me know if you think this is a bad idea 
 - OR to ask me more time to think about it. (On my side there is no urgency, so do not hesitate)

**Comment by jvermillard** [comment]
:+1:

**Comment by Warmek** [comment]
The only thing that we need is for https://github.com/eclipse/leshan url to be working and redirect to https://github.com/eclipse-leshan/leshan

**Comment by sbernard31** [comment]
> The only thing that we need is for https://github.com/eclipse/leshan url to be working and redirect to https://github.com/eclipse-leshan/leshan

This should done : Regarding [answers provided by Eclipse Team](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/449#note_1141465).

**Comment by sbernard31** [comment]
I give the green light to eclipse for the move : https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/449#note_1153533

**Comment by sbernard31** [comment]
**leshan** project was moved to its own **eclipse-leshan** organization that means that security advisors are now available.

I will update the [SECURITY.MD](https://github.com/eclipse-leshan/leshan/blob/master/SECURITY.md) file then I think we will be able to close this issue ?
