### ISSUE TITLE
Negative values handling for Write Attribute

### ISSUE THREAD

**Issue by PFnord** [eclipse-leshan/leshan#1451]
### Question

Hello everyone,

I am trying to have a HTTP PUT method that will handle negative values for Attributes. Does leshan not handle negative values for them? 
I have checked the code for DoubleAttributeModel and LongAttributeModel [here](https://github.com/eclipse/leshan/blob/b7e8a2d782ff20d8e04367f050435c40f899b7d2/leshan-core/src/main/java/org/eclipse/leshan/core/link/lwm2m/attributes/DoubleAttributeModel.java#L41,) but it seems to be checking for a DIGIT as the first char:

```
int start = parser.getPosition();
parser.consumeDIGIT();
```

This seems to throw an exception as the "-" sign (or % in the case of %2D) is not handled. So I have not found a way to use either curl or python requests library to write a negative attribute to my resource without altering the java code. Am I missing something?

Thanks in advance

**Comment by sbernard31** [comment]
> For Radio signal strength, the value is usually represented as negative, so using the greater than or less than should be, in general, a negative threshold.

:thinking: you maybe find a specification issue ?  At least, this seems NOT fixed in [LwM2m-v1.2.1](https://www.openmobilealliance.org/release/LightweightM2M/V1_2_1-20221209-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2_1-20221209-A.html#Table-732-1-lessNOTIFICATIONgreater-class-Attributes) ... 

Let's open an issue at OMA to try to get an answer : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/563

Please do not hesitate to add a comment to OMA issue above with your real use case :point_up:.

**Comment by sbernard31** [comment]
I hope we will get an answer :crossed_fingers:   
By the way, thx for reporting this :pray:

**Comment by sbernard31** [comment]
We can some news from OMA : 
 - https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/563#issuecomment-1781286828
 
 So I think I will adapt the code and this should be available for next milestone release 2.0.0-M14.

**Comment by sbernard31** [comment]
I created a PR about that : #1535

**Comment by sbernard31** [comment]
This is now integrated in `master` and should be available in next release 2.0.0-M14.

For pmin, pmax, epmin and epmax let's wait for OMA answer : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/563#issuecomment-1790424430

**Comment by PFnord** [comment]
That's a very nice change, thanks, I will try and test that locally!

**Comment by sbernard31** [comment]
Some more question about attribute type : https://github.com/eclipse-leshan/leshan/issues/1583
