### ISSUE TITLE
My device cannot use the X509 certificate method to connect to the leshan public server

### ISSUE THREAD

**Issue by 1103168331** [eclipse-leshan/leshan#1455]
### Question

Hi ，My device used no authentication or PSK authentication method to connect to the leshan server before, and it worked very well. Recently, I tried to use X509 to connect:
1. I register the X509 authentication method on the server page and download the server certificate
2. Then, import the certificate to my device and try to connect to the server
3. I observed that my device and the server have completed the DTLS handshake
4. The device sends an LWM2M registration request, which is rejected by the leshan server

My confusion is, the completion of the DTLS handshake proves that the X509 authentication process has ended, why did the server reject my device request? This looks like a BUG
Upload the wireshark log captured by my device.
[wireshark_log.zip](https://github.com/eclipse/leshan/files/11703782/wireshark_log.zip)

**Comment by sbernard31** [comment]
#### My guess :
This looks like a missmatch between **Certificate Common Name (CN=)**  and **client endpoint name** .

#### Current Leshan Behavior:
Currently when using X509 Leshan Server check if Common Name (CN=) in Certificate is equal to client endpoint name.
If it doesn't match it returns an error(probably a 4.03 Forbidden) on Registration Request. 

#### What says LWM2M specifications:
How Client certificate must be validated at Server side is not crystal clear to me.

In very old version of the specification, I'm talking about an old Candidate version for v1.0 (just before the official v1.0 release), it was said : 
>  A LWM2M Client Certificate MUST include the Endpoint Name parameter used to register the device in the Subject Common Name (CN) field of the Certificate. 

(Source : ([LWM2M-v1.0-20160407-C§7.1.3 X.509 Certificates](https://www.openmobilealliance.org/release/LightweightM2M/V1_0-20160407-C/OMA-TS-LightweightM2M-V1_0-20160407-C.pdf)))

Then in official v1.0.x or v1.1.x release, there is nothing more about this. 
The only remaining hint about that is at [LWM2M-v1.1.1@transport§Table: 6.7.-2 Response Codes: Client Registration Interface](https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#Table-67-2-Response-Codes-Client-Registration-Interface) (You should find same table in LWM2M v1.0.x): 
> 

Available CoAP Response Codes | Reason Phrase
-- | --
4.00 Bad Request | Endpoint Client Name does not match with CN field of X.509 Certificates



When looking at [LWM2M-v1.2.1@transport§5.2.9.3. X.509 Certificates](https://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_2-20201110-A.html#5-2-9-3-0-5293-X509-Certificates), you can find some more hints : 
> Client certificates SHOULD contain the endpoint client name in the subject CN (Common Name) attribute. The LwM2M Server MUST perform the security checks outlined in [5.2.6. Endpoint Client Name](https://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_2-20201110-A.html#5-2-6-0-526-Endpoint-Client-Name).

**Comment by 1103168331** [comment]
Thanks for your suggestion, I'll regenerate a certificate and test again.

**Comment by 1103168331** [comment]
Hi @sbernard31 

Your suggestion is correct, now I can use X509 to connect to leshan public server, thank you very much for your help.

But now I have encountered a new problem: when I try to use BS+X509 to connect server, I am asked to enter my client certificate and private key. After I enter it, I encounter the following error. I think my certificate and private key match, can you please help to check what is causing this error？

my certification:
308202DD3082024602143FD931CA93775059B082476C2F1A85C06625A215300D06092A864886F70D01010B0500306B310B300906035504061302434E310E300C06035504080C057761746572310E300C06035504070C0557415445523110300E060355040A0C075175656374656C310A3008060355040B0C0151310B300906035504030C0251553111300F06092A864886F70D01090116025858301E170D3233303631303038303130385A170D3333303630373038303130385A306C310B300906035504061302434E310A300806035504080C0131310B300906035504070C0248463121301F060355040A0C18496E7465726E6574205769646769747320507479204C74643121301F06035504030C1875726E3A696D65693A38363834393430363030303133393930820122300D06092A864886F70D01010105000382010F003082010A0282010100F377E1D6DEBFD787BFD09C115CD4ABC7BF60C0BA4A78CC6F36621A04DE2836FD018DECC0892C14F909842B06E2817145ACFDD8E7AC73FFD85E4CA0BCBFF4A476A903FA6FDBFB55AE71882F5FDF22021DA8D3F2775F67C3D12800D7A9E8CF2E102914FAA759646792A8B845AF6D9453A44441EA7842A3CAA67E3A38171479946D321CC94BABDA1E3BCEB4573F0C1861057CB553897B9FA852D0D0FD4BC5404E4156F619BA59DC7E4FCAF8BC647747B5AB5CF49054EAD8B3A5AF832060A9B321A65CAA7F59192622011A019BF83AD6B84159C5FA5723F0764A1FBCE636764D512C5A4295B5E3B78D9EEB04FC302C052D6D4E1F1688B08970C5BE364AA7F6A3D3AD0203010001300D06092A864886F70D01010B050003818100A209A7545FCB896F0B9345BFB9E552EFB6B5123F9B4FDE6C7402AF9A0570BF6E27897B234D56AB740BC18AF9E06825810C7776AAF122EBEE44139AE76E4A7CD2DA8FB926960685B838F0F3B2A467EE6E0F0AB49D5D4E98DD0D29DA78A4717B8F491267F5118930E4D0BFB149F6D072E579F36AA5665DF756654243ADAD8F4171

my private key:
308204BD020100300D06092A864886F70D0101010500048204A7308204A30201000282010100F377E1D6DEBFD787BFD09C115CD4ABC7BF60C0BA4A78CC6F36621A04DE2836FD018DECC0892C14F909842B06E2817145ACFDD8E7AC73FFD85E4CA0BCBFF4A476A903FA6FDBFB55AE71882F5FDF22021DA8D3F2775F67C3D12800D7A9E8CF2E102914FAA759646792A8B845AF6D9453A44441EA7842A3CAA67E3A38171479946D321CC94BABDA1E3BCEB4573F0C1861057CB553897B9FA852D0D0FD4BC5404E4156F619BA59DC7E4FCAF8BC647747B5AB5CF49054EAD8B3A5AF832060A9B321A65CAA7F59192622011A019BF83AD6B84159C5FA5723F0764A1FBCE636764D512C5A4295B5E3B78D9EEB04FC302C052D6D4E1F1688B08970C5BE364AA7F6A3D3AD0203010001028201003544DE89C7B4CBB06CDC74B92BC9704844EC235EDF1A6D084C2ACCAC91FAD48528C8E7AAFC984382757D9078722886230B8582E6B589AFC9A46039AEF284D1531109C8CA9EA3F00C39D4E520A1CE6C0E1739404CB3F81D14EF1EB810F9DA12A70086118D79F688DEC2C186A5AA6110A7D9335EDCAF1FED1FDE7058835C3C79A7B9525ADC2E1126781D3B1EE1519B243912ED0BB91288E1E7769E3031D80B43B42547E05B6A55CFE88B7F0623A311C9A9135B6C6EADB43B5A7617AE6CBC301E6EAC48CA355A07005CE47B4C61FAA3AD456DBABA1DD08AE38A674907DE15BDCD4B5283F99AD194FAF7EC31AB415D548B8E26085A752A2C65335D6034B2661E54E102818100FE3132366999AB1B50204268A2A6A78F0BC83704B034EF1469D6BB70F3488D7213EFA5D39CCE2BEF05EA56545051F700A2896A80E59CFAF60041ED166DC1733F08C520DDB053D1734BF96962C19233D0574E388BFDC5A136811647D7B8BE44D5F394D60FE2D71E5876427A298602B5FB041AE63D2DCB39AA9A5AA5290EFC236502818100F5332946691849AF384DA13F2AC0B17150852843A0041CBC102512B40E61BC490EDB6EB7F7D346B69E9B9273E53BE54948B3877C0952C4E74A3CD1290410C554C3E6655140DBFBF76483D5B92E1C66FFD1ABF1FCF2C5CC6508CCA9590D5D93657474CB4AE4E76C627BA893A58D1B12148C59C4E5C0BCE7C07CEFB1CDC4463EA90281807B2947150A3184B065305C3CEAA22909AC41C436A751DE8D5B82C9AB3E9566C361597A557FE27D7300C0BC3779FB5CDC97E451104730BA803B3BB62E69DB938575305E6E4BA33116D636F093030B5DC392A9B9C84A9B593359747C36CFB29113C143DA3C3442DAD72DE5A3DF3EA94D976433CC5ED43365AB7DC271C7E514D1E902818035F36FDD823A49DC37F33CCB7D48B0C252093A76C6BAA0E7F05577EC0E4E0AF3B84527F36AA01E2B08730AA25D89F4454FADD0DDC5DF645BCFC5D9EFC06940420A68A35A617F05CDC55C0CA69632C1A70027693352E79AB5905E17D4F44FE6A2A8211AA9FBFBBFA95BB417E89147A78EC5E2EAA3F2E89DC588B7E4D375A04F2102818100E46A6ADC799F51D97E0CEC2F26768E6EDC57A13E9B0E6D7703DCBCAEE8F1F2C5B652CE5142BE896076019C0E04C8C9B8A941C60B7D28488ECA2182EA0174F8912E8E465B83117A7567825A537F0DA358D79B8F0E6728BF62EAE32E74C8A8BF021E5670E5CFD532F12239E56E73DEFFCF8572816F9A5CFCDE78F5C4FFDA65CC0F
![cannot upload private key](https://github.com/eclipse/leshan/assets/108513828/c077b9ef-4f35-42b7-b8cb-a8350785a1fe)
[pkcs8_102_cert_key.txt](https://github.com/eclipse/leshan/files/11752177/pkcs8_102_cert_key.txt)
[certificate+key.zip](https://github.com/eclipse/leshan/files/11752189/certificate%2Bkey.zip)

**Comment by sbernard31** [comment]
> Yes, i looked it before 

OK that was just to rule out this kind of issue. 

> anyway, i will generate a EC key and try again.

Let me know if using EC key works for you.

> the difference is this page introduce how to generate EC key, but in my project, i use RSA key

I'm not 100% but  I seem to remember vaguely that encryption has been depreciated ? see https://en.wikipedia.org/wiki/Transport_Layer_Security#Algorithms.

Anyway, I'm not sure **leshan-bsserver-demo** perfectly behave with RSA key. When I will find time I will try to have a look at this using file you provide just above :point_up:

**Comment by 1103168331** [comment]
I changed the key type and after that when I used EC key my problem was solved. Thank you for your reminder.

It seems that leshan cannot parse RSA key normally, will this function be supported in the future?

**Comment by sbernard31** [comment]
> It seems that leshan cannot parse RSA key normally, will this function be supported in the future?

I will try to have look at this in next few days/weeks, I should : 
 - verify if RSA key can be used in LWM2M
 - see if the current leshan limitation is about **leshan-bsserver-demo** only or *leshan library too**. 
 - see what would be the impact to support it.

**Comment by sbernard31** [comment]
About : 
> verify if RSA key can be used in LWM2M

I understand this is not strictly forbidden to use RSA but this is strongly recommended to use ECC

The [LWM2M specification](https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#5-2-8-3-0-5283-X509-Certificates) says : 
> The X.509 certificates SHOULD be conformant with the profiling given in [RFC7925]. 

And [RFC7925](https://www.rfc-editor.org/rfc/rfc7925#section-4.4.4) says that : 
- `signature` must be `ecdsa-with-SHA256` or stronger
- `signatureAlgorithm` must be `ecdsa-with-SHA256` or stronger
- `subjectPublicKeyInfo` must be  `id-ecPublicKey` algorithm 

>   There are various cryptographic algorithms available to sign digital
   certificates; those algorithms include RSA, the Digital Signature
   Algorithm (DSA), and ECDSA.  As Table 1 shows, certificates are
   signed using ECDSA in this profile.  This is not only true for the
   end-entity certificates but also for all other certificates in the
   chain, including CA certificates.  This profiling reduces the amount
   of flash memory needed on an IoT device to store the code of several
   algorithm implementations due to the smaller number of options.
   
Note also that : key size of ECC is about an order of magnitude smaller then RSA/DSA for same level of security. (See :https://www.rfc-editor.org/rfc/rfc7925#section-20)

@1103168331, knowing all those information do you still need support of RSA ? 
@1103168331, just to be sure you are able to use RSA Certificate to connect LWM2M client to LWM2M server but you are not able to create a bootstrap configuration which try to write RSA Certificate on the client, right ? 

@jvermillard do you have any opinions about this ?


(Now I will look at :  "see if the current leshan limitation is about **leshan-bsserver-demo** only or leshan library too*)

**Comment by sbernard31** [comment]
> if the current leshan limitation is about leshan-bsserver-demo only or leshan library too

I just check and currently there is code which limits usage of RSA key in : 
-  :x:  **leshan-server-demo** and **leshan-bsserver-demo** : `SecurityUtil` which is responsible to load file + `PublicKeySerDes` for REST API (only workaround modifying Leshan code)
-  :x:  **leshan-client-demo** : `SecurityUtil` which is responsible to load file (only workaround modifying Leshan code.)
-  :x:  **Leshan Boootstrap Server library** (not demo) refuse RSA Key for Bootstrap Config because of `ConfigurationChecker` but it is only used for `InMemoryBootstrapConfigStore` and a Custom `ConfigurationChecker` can be provided)
- :x:  **Leshan Client  library** (not demo) refuse RSA key this is in static code and behavior can not be changed without modified Leshan code.

:heavy_check_mark:  Only **Leshan Server library** (not demo) support RSA Key out of the box. 

Here is crappy code I used to test usage of RSA : https://github.com/eclipse/leshan/commit/3397b837f04e84512d0b74f31a10277a3b3958fb (from [`test-rsa`](https://github.com/eclipse/leshan/tree/test_rsa) branch)

To generate certificate and key I used : 
```bash
# To generate  RSA keys
openssl genrsa -des3 -out rsa-prik.pem 2048 
# To convert it from PEM to  DER encoding
openssl pkcs8 -topk8 -inform PEM -outform DER -in rsa-prik.pem -out rsa-prik.der -nocrypt
# Create self signed certificate
openssl req -key rsa-prik.pem -new -out rsa.csr  
openssl x509 -signkey rsa-prik.pem -in rsa.csr -req -days 365 -out rsa-cert.der -outform DER 
# To convert in Hexa decimal 
xxd -p -c 512 myFileToConvert
```

**Comment by sbernard31** [comment]
So questions are : 
1. Should we want to support RSA knowing this seems to have not so much benefits compare to EC and knowing this is not really recommended by LWM2M specification ( See https://github.com/eclipse/leshan/issues/1455#issuecomment-1603999197)? 
2. If, yes how should it looks like ? 
    1. Do you want to allow if at library level only OR in demo too ?
    2. Do we want servers  to only support exclusively RCA or EC at a time (easy one) OR do we want them to support both RSA and EC (maybe more ?) at same time, which means we need to be able to select right certificate depending of client supported ciphersuite (see https://security.stackexchange.com/questions/133409/link-between-cipher-suites-and-certificate-key)

**Comment by sbernard31** [comment]
@msangoi, @jvermillard, @JaroslawLegierski  any opinions ? 
Do you know if this is something which could be needed for you at short/mid term ?

**Comment by JaroslawLegierski** [comment]
> We don't plane use such features in the short/mid time.

**Comment by 1103168331** [comment]
No comment, thanks for your support !!

**Comment by sbernard31** [comment]
@1103168331  does it mean that you finally decide to not use RSA certificate ?
