### ISSUE TITLE
It should be possible to create Leshan Demo Client without PSK identity

### ISSUE THREAD

**Issue by Warmek** [eclipse-leshan/leshan#1462]
### Question

Not providing security.serverPublicKey makes Leshan Demo Client crash, despite this field is not necessary when using PSK authentication

**Comment by sbernard31** [comment]
I don't understand. Please share steps to reproduce.
I guess you are using **leshan-client-demo** command line, so share the more simple command line which allow to reproduce the issue.

**Comment by sbernard31** [comment]
Maybe this is relative to this issue : https://github.com/eclipse-leshan/leshan/issues/1316

**Comment by Warmek** [comment]
Yes. That's what I meant

**Comment by Warmek** [comment]
Yes. Sorry for a duplicate
