### ISSUE TITLE
Requests not working with Docker specifically

### ISSUE THREAD

**Issue by ferrveciana** [eclipse-leshan/leshan#1489]
### Question

I have an implementation of lwm2m server/client. For now, I'm only using read requests which work just fine with my local machine IDE. 
When creating the docker image and launching both the client and server, the registration seems to work as well, but any read request returns the following error:

![image](https://github.com/eclipse-leshan/leshan/assets/27004210/cdddeaeb-63ef-46c7-9431-352bc7a46006)

I use custom ports but this shouldn't be the issue since the initial device registration works.
I don't know what I should try next, do you have any ideas? Could this be some sort of bug?

**Comment by ferrveciana** [comment]
Extra info:
![image](https://github.com/eclipse-leshan/leshan/assets/27004210/1fc1266b-f7d5-4d01-9aea-06b2c9329d6f)
Here are the server logs receiving the device registration.

![image](https://github.com/eclipse-leshan/leshan/assets/27004210/efc18da4-33f3-4355-afb0-d7c0e5f46a59)
device port configuratioin

![image](https://github.com/eclipse-leshan/leshan/assets/27004210/42bcbd55-f82e-4a29-b390-b2db226488b8)
server port configuration

**Comment by sbernard31** [comment]
Hi, sorry for delay.

First,  please :pray:  when you share textual information, do not use image.... (unless there is a good reason to use it instead of text...)

Looking at the stack trace the NPE is in your code. If seem the read request time out and so you can `null` for the response.
And you didn't handle the timeout case correctly.

```
   /**
     * Send a Lightweight M2M request synchronously using a default 2min timeout. Will block until a response is
     * received from the remote server.
     * <p>
     * The synchronous way could block a thread during a long time so it is more recommended to use the asynchronous
     * way.
     * <p>
     * We choose a default timeout a bit higher to the MAX_TRANSMIT_WAIT(62-93s) which is the time from starting to send
     * a Confirmable message to the time when an acknowledgement is no longer expected.
     *
     * @param destination The {@link Registration} associate to the device we want to sent the request.
     * @param request The request to send to the client.
     * @return the LWM2M response. The response can be <code>null</code> if the timeout expires (see
     *         https://github.com/eclipse/leshan/wiki/Request-Timeout).
     *∕
```

 And also, like the javadoc says, It is strongly recommended to use asynchronous API especially in `RegisterListener`. 
 See : 
 ``` java
 /**
 * Listen for client registration events.
 * <p>
 * Those methods are called by the protocol stage thread pool, this means that execution MUST be done in a short delay,
 * if you need to do long time processing use a dedicated thread pool.
 */
public interface RegistrationListener {
```
My first bet  that problem should be more or less like this one : https://github.com/eclipse-leshan/leshan/issues/507#issuecomment-392525744
Using async send should solve it.

**Comment by ferrveciana** [comment]
You are a live saver! Using the async send did work!

Thank you!

**Comment by sbernard31** [comment]
Glad to help :wink:
