### ISSUE TITLE
ReadRequest unable to retreive payload

### ISSUE THREAD

**Issue by ferrveciana** [eclipse-leshan/leshan#1500]
### Question

I am using lesan 2.0.0-M11

My client has this
```
sendService.sendData(serverIdentity, ContentFormat.SENML_JSON, List.of("3443/0/3/"), 1000, responseCallback, errorCallback);
```

on the server side 

```
 @Override
    public void dataReceived(final Registration registration, final TimestampedLwM2mNodes data, final SendRequest request) {
        CommunicationProtocolThreadLocal.setCommunicationProtocol(CommunicationProtocolEnum.LWM2M);
        final LwM2mPath lwM2mPath = new LwM2mPath(3443, 0, 3);
        final String prettyString = data.getNodes().values().stream().findFirst().get().toPrettyString(lwM2mPath);
        //TODO how to get the data from here
        //final LwM2mNodeOpaqueEncoder lwM2mNodeVisitor = new LwM2mNodeOpaqueEncoder();
        // data.getNodes().values().stream().findFirst().get().accept((LwM2mNodeVisitor) lwM2mNodeVisitor);
     }
```
I do have the data, I can see it when debugging but I can't find a way to get it out
![image](https://github.com/eclipse-leshan/leshan/assets/27004210/a1b1112f-4299-4e36-a964-6568d50ef3e9)

There is no .getValue function or anything similar. I also tried the LwM2mNode functions like the toPrettyString which tells me the correct size and path but not the payload. I can't make the accept() work, but I don't know if that would help either.

I could not find any examples or detailed documentation about this anywhere, other than reading the code, the Javadocs, and the forum, if you know anywhere else I could read about this, it would also be helpful.

Thanks!

**Comment by sbernard31** [comment]
getNodes() could return object, object instance, single resource, multiple resource or resource instance.

So it's up to you to cast the node to the expected type .

```java
LwM2mResource resource = (LwM2mResource) data.getNodes().get(new LwM2mPath("3443/0/3/"));
resource.getValue();
```

**Comment by ferrveciana** [comment]
Yup that was it.. thanks! ^^
