### ISSUE TITLE
Server-initiated Bootstrap DTLS

### ISSUE THREAD

**Issue by imSeungJin23** [eclipse-leshan/leshan#1508]
### Question
Hi, @sbernard31 
I am developing using version 1.4.2.
I would like to implement a secure server-initiated bootstrap function.
When using secure bootstrapping, a secure session must be enabled.
I tried the handshake procedure using dtlsconnector, but the connector cannot be used because the address is bound when the bootstrap server runs.
Since the client communicating with the bootstrap server is also assigned an address, I am not sure how the handshake procedure should proceed.

I want to initiate the handshake process by sending a ClientHello from the bootstrap server to the client.
Thank you

**Comment by imSeungJin23** [comment]
First of all, thank you for your reply.
I am trying server-initiated bootstrapping on a client other than leshan-client-demo.

Currently, for testing, we are sending a clienthello to dtls-server (it is a bootstrap server, but like a client) to start the handshake and waiting for a session connection.

  Since ClientHello is not being sent, there is nothing to call a log...

**Comment by sbernard31** [comment]
>  I am trying server-initiated bootstrapping on a client other than leshan-client-demo.

And you are using **leshan-bsserver-demo** ?

> Since ClientHello is not being sent, there is nothing to call a log...

So how do you know :  _" the connector cannot be used because the address is bound when the bootstrap server runs."_ ? :thinking: 

>  I am trying server-initiated bootstrapping on a client other than leshan-client-demo. 

Does it work with **leshan-client-demo** ?

> Currently, for testing, we are sending a clienthello to dtls-server (it is a bootstrap server, but like a client) ...

I don't get you. 

> I tried the handshake procedure using dtlsconnector, but the connector cannot be used because the address is bound when the bootstrap server runs.

I'm not sure I get you too...  but If you are **not** using **leshan-client-demo**, maybe your client bind to same address than "dtls-server" ?

**Comment by sbernard31** [comment]
> I am trying **server-initiated** bootstrapping on a client other than leshan-client-demo.

Oh I just get that you are talking about **server-initiated bootstrap**

So that means you also need a **LWM2M server**, see : https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-1-3-4-0-6134-Server-Initiated-Bootstrap

**Comment by imSeungJin23** [comment]
Yes, I am using leshan-bsserver-demo.

I looked at the document you referenced, but what if it is not registered on the lwm2m server?

**Comment by sbernard31** [comment]
> When the connector is activated, it appears on the console.

I didn't get if what you call connector is at client or server side ? 

>  I want to send a ClientHello from leshan-bsserver-demo (I want the bootstrap server to act as a client).

OK much clear now. 

1) This is out of specification, so not good for interoperability. 
2) By default, LeshanBootstrapServer can not initiate handshake. (see [ LeshanBootstrapServer.build()](https://github.com/eclipse-leshan/leshan/blob/1.x/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/bootstrap/LeshanBootstrapServerBuilder.java#L542C13-L544))
3) Note that in this case your client will need to act as DTLS server. Some client are not able to do that. 
4) Note that a bootstrap server can not send Execute request and so a well implemented device should reject an execute request on resource /1/x/9 from a bootstrap server.

> I looked at the document you referenced, but what if it is not registered on the lwm2m server?

Again [this is not specified](https://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-1-3-4-0-6134-Server-Initiated-Bootstrap), so this can be anything : 
_"Note: proprietary mechanisms can be used to cause a LwM2M Client to enter the standard "Client Initiated Bootstrap" mode, but that is outside the scope of this specification."_

So, this is out of Leshan project scope.

**Comment by imSeungJin23** [comment]
Thanks, I'll have to find another way. 👍

**Comment by sbernard31** [comment]
Sorry I missed this question.

Yes the Leshan LWM2M server is able to initiate a Handshake with a client.
But some warning : 
 1. As I said I'm not sure all client are able to do that.
 2. I don't know if this is strictly follow the specification I tried to get some input from OMA about this but without success... (a lot to read at : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/410 )

**Comment by imSeungJin23** [comment]
Thank u !

**Comment by sbernard31** [comment]
Should we close the issue ?

**Comment by imSeungJin23** [comment]
Yes
