### ISSUE TITLE
Include Test Object ID range 42769-42800

### ISSUE THREAD

**Issue by rw-wep** [eclipse-leshan/leshan#1513]
### Question

The OMA LwM2M registery (https://technical.openmobilealliance.org/OMNA/LwM2M/LwM2MRegistry.html) has a ObjectID Class category "Test" which consists of IDs in the range 42769-42800.

Currently leshan (or at least the web-server-demo) does not accept any Object IDs > 42768, so XML-Objectdescriptions with IDs in the Test range are rejected by leshan during startup.

I think it would make sense for leshan to accept Object IDs in the test range as this is useful during prototyping.

**Comment by sbernard31** [comment]
Yep, I guess this should be accepted.

I didn't remember about that range :thinking:. Is it something new ? 

Looking quickly at the code, this should be adapted : 
https://github.com/eclipse-leshan/leshan/blob/6e62e54e72d90bc3f335af533d5e7d53e3718f37/leshan-core/src/main/java/org/eclipse/leshan/core/model/DefaultObjectModelValidator.java#L49-L60

And also maybe URN validation is too strict ? :thinking: 
https://github.com/eclipse-leshan/leshan/blob/6e62e54e72d90bc3f335af533d5e7d53e3718f37/leshan-core/src/main/java/org/eclipse/leshan/core/model/DefaultObjectModelValidator.java#L138-L179

**Comment by jvermillard** [comment]
Would this impact the URN "kind"?
https://github.com/eclipse-leshan/leshan/blob/master/leshan-core/src/main/java/org/eclipse/leshan/core/model/URN.java

**Comment by rw-wep** [comment]
> I didn't remember about that range 🤔. Is it something new ?

Yeah, the ID ranges where changed at some point, but I am not sure when exactly. Before the change there was a range of IDs that could be used without any registration for custom objects (in the 30000 range as far as I remember). But now it seems everything up to 42768 is reserved and the Test Object IDs where added.

> And also maybe URN validation is too strict ?

Right. At least for the Test Id range this might be an issue, as OMA does not seem to define a URN for that range.

**Comment by sbernard31** [comment]
@rw-wep  thx for taking time to report that !

> Would this impact the URN "kind"?

@jvermillard  Yep this code should probably be adapted too. :+1:

**Comment by sbernard31** [comment]
> Right. At least for the Test Id range this might be an issue, as OMA does not seem to define a URN for that range.

I tried to get an answer about that : https://github.com/OpenMobileAlliance/lwm2m-registry/issues/737

**Comment by sbernard31** [comment]
> MA does not seem to define a URN for that range.

@rw-wep, in your case what looks like  URN ?

**Comment by sbernard31** [comment]
I created a PR about that : https://github.com/eclipse-leshan/leshan/pull/1515

For now, it skips URN validation for test range ... I don't understand why OMA didn't define a URN pattern for test (e.g. : `urn:oma:lwm2m:test:<id>:<version>`)

**Comment by sbernard31** [comment]
@rw-wep let me know if you review it and/or if you're able to test it.

**Comment by rw-wep** [comment]
Looks good so far.
The objectdescription-file (id 42772) I test with has a blank URN field.
It can be loaded without errors and it shows up in the leshan-web-server-demo when a device connects with such an object.

**Comment by sbernard31** [comment]
I integrated PR #1515 in `master`

About Test URN format,  we will see if we get an answer from OMA. 

Waiting I think we can close this issue.

@rw-wep thx again for your time.  :pray:
