### ISSUE TITLE
Error handling improvement in SendHandler

### ISSUE THREAD

**Issue by JaroslawLegierski** [eclipse-leshan/leshan#1524]
### Question

Please find [here](https://github.com/eclipse-leshan/leshan/compare/master...JaroslawLegierski:leshan:opl/handling_error_improvement) small modification proposal in SendHandler. The main aim of this modification is based on new InvalidSendRequestException which could allow us to characterize the error better. What is your opinion about this change ?

**Comment by JaroslawLegierski** [comment]
We can reuse InvalidRequestException instead of InvalidSendRequestException. This solution is also OK for us.

**Comment by sbernard31** [comment]
Integrated in **master**, thx for contribution :pray:
