### ISSUE TITLE
Add Observe Active Cancel support to leshan-server-demo

### ISSUE THREAD

**Issue by sbernard31** [eclipse-leshan/leshan#1538]
This is about  : 
- [x] add REST API to server demo.
- [x] add UI to be able to call this API.

This will be useful for `coap+tcp` support (#1528) because passive cancel doesn't exist with `coap+tcp` : https://github.com/open-coap/java-coap/issues/71

REST API is need for Zephyr integration tests : #1537.

I have not clear idea about how the UI could looks like, if you have idea do not hesitate to share.

**Comment by sbernard31** [comment]
REST API was added with commit : 2afadfcc35f8ab78d471eee8f95c6213607e8ad5

API looks like : 
``` bash
# For "classic" observe : 
curl -i  -X DELETE  "http://{yourserver.url}/api/clients/{your_device_endpoint}/{your_node_path}/observe?active"
# Example : 
curl -i  -X DELETE  "https://leshan.eclipseprojects.io/api/clients/my_device/3442/observe?active"

# For "Composite" observe : 
curl -i  -X DELETE  "http://{yourserver.url}/api/clients/{your_device_endpoint}/composite/observe?paths={list_of_paths}&active"
# Example : 
curl -i  -X DELETE  "https://leshan.eclipseprojects.io/api/clients/my_device/composite/observe?paths=/3/0/1,/3/0/2,/3/0/13&active"

```

**Comment by SeppoTakalo** [comment]
@sbernard31 Thank you.
This seem to work. I can now do both, passive or active cancellations:

![image](https://github.com/eclipse-leshan/leshan/assets/3104794/fb95863e-02d0-4793-8b0d-46a7b4529685)

**Comment by sbernard31** [comment]
Great :+1: 
Thx a lot for taking time to validate that :pray:

**Comment by sbernard31** [comment]
#1555 is now integrated in `master`.
