### ISSUE TITLE
bootstrap webpage display blank

### ISSUE THREAD

**Issue by Bradymu** [eclipse-leshan/leshan#1545]
### Question

Hello
today bootstrap Web page cannot open, display blank, is there any fault caused by this situation.  We changed the browser and the computer to try to open the web page, the situation is the same.
![image](https://github.com/eclipse-leshan/leshan/assets/151825674/5f69d8fe-f374-48e1-978f-585741d19d50)

**Comment by sbernard31** [comment]
Yep it seems there is something wrong here.
I will try to fix it. 
Thx for reporting this  :pray:

**Comment by sbernard31** [comment]
OK I maybe find it. :detective: 

Recently we migrate from `vue-cli` to `vite` to build our web demo front-end. (https://github.com/eclipse-leshan/leshan/issues/1540)
By default `vite` uses absolute URL `/` but when we deploy it on our sandbox we do some proxy rewrite to serve **bserver-demo** on `/bs/` and with absolute path this doesn't works ...

So, l changed it to relative path `./` hoping this will solve the issue.  (commit fa6f7d2)

**Comment by sbernard31** [comment]
It seems to work :relieved:.

Let me know if this works for you too and if it works you can close this issue :pray:

**Comment by Bradymu** [comment]
It is ok, thanks!
