### ISSUE TITLE
whether the operation procedure is correct?

### ISSUE THREAD

**Issue by Bradymu** [eclipse-leshan/leshan#1547]
### Question

1.My adding client operation procedure in below attachment, could you pls help to check the procedure is wrong to make PSK failed (question follow#1543)
2. Did the PSK for bs server and DM server must be the same?
Endpoint name: rw001
my PSK info is below.
bootstrap server:
**iot_app_100**
8c455cea1475443266418f1600b231a1c92b2adedd2526f36bf61ab132976a1c

DM server:
**iot_app_123**
9c2b4bfa9846a60747415cbcb703caaedaea6600346275232c9da5ceaaaeb5da

![step1](https://github.com/eclipse-leshan/leshan/assets/151825674/a8936183-1fb1-4f4d-a2fc-1e81a7ae8e57)
![step2](https://github.com/eclipse-leshan/leshan/assets/151825674/e727d01d-15b2-474c-b458-d708b46d8561)
![step3](https://github.com/eclipse-leshan/leshan/assets/151825674/dbf2e445-726f-4239-9b9a-4aa5554d90e4)
![step4](https://github.com/eclipse-leshan/leshan/assets/151825674/da463d58-545a-4902-91cb-787729847a4c)
![step5](https://github.com/eclipse-leshan/leshan/assets/151825674/a8acc583-d0c9-40a3-a67a-ab7b48ff507c)
![step6](https://github.com/eclipse-leshan/leshan/assets/151825674/be22cff8-e99c-4369-a12a-61445fb87f37)

Thanks!

BRS

**Comment by sbernard31** [comment]
> Did the PSK for bs server and DM server must be the same?

No.  
It is even recommended to not used the same. (like it is recommended to you to not used same login/password for all your service account)


> My adding client operation procedure in below attachment, could you pls help to check the procedure is wrong to make PSK failed 

I see nothing wrong.

> (question follow #1543)

Maybe not needed to multiply github ticket, if this is still about same issue.

**Comment by sbernard31** [comment]
Closed because : https://github.com/eclipse-leshan/leshan/issues/1543#issuecomment-1827434451
