### ISSUE TITLE
SENML_JSON encoder modifications proposal

### ISSUE THREAD

**Issue by JaroslawLegierski** [eclipse-leshan/leshan#1554]
### Question

1. Timestamp coding in SENML_JSON encoder 

Currently leshan SENML_JSON encoder can encode following records:
```json
[
	{
		"bn": "/3303/0/5700",
		"bt": 1699877805.766,
		"v": -128.8
	},
	{
		"bn": "/6/0/0",
		"bt": 1699877805.800,
		"v": -39.0
	}
]
```
can we change this format to following one: ?
```json
[
	{
		"bn": "/3303/0/5700",
		"bt": 1699877805.766,
		"v": -128.8
	},
	{
		"bn": "/6/0/0",
		"t": 0.101,
		"v": -39.0
	}
]
```

2. Support of mixed data (with and without timestamps)

Is it possible to modify the encoder to support mixed data with timestamp and without it in one SENML record e.g.:
```json
[
	{
		"bn": "/3303/0/5700",
		"bt": 1699877805.766,
		"v": -128.8
	},
	{
		"bn": "/6/0/0",
		"v": -39.0
	}
]
```

**Comment by sbernard31** [comment]
I must confess that I didn't get your point. I will try to summarize my understanding.

**SenML is not a one to one encoding format.** 

There is several way to encode a given data in valid SenML format. 

All those valid SenML example express exactly the same thing
```json
{"bn":"/base/", "n":"name1", "v":101},
{ "n":"name2", "v":102},
{ "n":"name3", "v":103},
```
```json
{ "n":"/base/name1", "v":101},
{ "n":"/base/name2", "v":102},
{ "n":"/base/name3", "v":103},
```
```json
{"bn":"/base/name1", "v":101},
{"bn":"/base/name2", "v":102},
{"bn":"/base/name3", "v":103},
```

**Leshan Decoder* 

As SenML is not a one to one encoding format,  Leshan Decoder should be able to decode any possible way to express data in SenML. 

Currently, I think Leshan Default SenML decoder to that. 

**Leshan Encoder* 
About encoding, Leshan should choose a way to encode which a a valid one. 

Currently, I think Leshan Default SenML encoder to that. 


**Questions **

Just to be sure I understand you : 
 - do you agree that current encoding is valid ?
 - What would be the point about changing the current encoding behavior ? is it an optimization purpose (e.g. reduce payload size) ?

**Comment by JaroslawLegierski** [comment]
> * do you agree that current encoding is valid ?
> 
Yes I think current encoding is valid.

> * What would be the point about changing the current encoding behavior ? is it an optimization purpose (e.g. reduce payload size) ?

I was thinking about using  in [this test](https://github.com/JaroslawLegierski/leshan/blob/45ec9410ffe99040bdbe835ec98366abb7359564/leshan-integration-tests/src/test/java/org/eclipse/leshan/integration/tests/observe/ObserveCompositeTimeStampTest.java#L124) the same data structure as produces Ioterop SDK, but finally we can leave it as is.

**Comment by sbernard31** [comment]
Oh ok, this was just about writing test, I get it now :thinking:. I don't think this is a good reason to change default leshan encoder behavior.

But it could make sense to add Decoder tests with different kind of encoding than the one used by Leshan Encoder.
So, If you think this is a good idea and if you want to do it,  you could add test about that  : 
 - to the existing `LwM2mNodeDecoderTest` class
 -OR to a new class `LwM2mNodeSenMLDecoderTest` class (currently it does not exist)

**Comment by sbernard31** [comment]
with #1577 integrated, I guess we can close this issue. 

(If I was wrong do not hesitate to reopen)
