### ISSUE TITLE
Did leshan bootstrap server support BLOCKWISE in CoAP

### ISSUE THREAD

**Issue by Bradymu** [eclipse-leshan/leshan#1568]
### Question

we use Leshan bootstrap server in NO security, client connect to Leshan bootstrap server and bootstrap send the DM server information and certificate information to client. but client receive block, but from the log, the two blocks in CoAP packets didn't match for the token being different and so error 4.08 is returned.

wireshark package:
![image](https://github.com/eclipse-leshan/leshan/assets/151825674/e68ff980-9096-4057-8b7d-63112259a50b)
[tcpdump1221.zip](https://github.com/eclipse-leshan/leshan/files/13740259/tcpdump1221.zip)
bootstrap server log below

Send WRITE request on /0/1 using TLV(11542)
/0/1/0 : "coaps://leshan.eclipseprojects.io:5684"
/0/1/1 : false
/0/1/2 : 2
/0/1/3 : 425 Bytes
/0/1/4 : 556 Bytes
/0/1/5 : 138 Bytes
/0/1/6 : 3
/0/1/7 : 0 Bytes

/0/1/8 : 0 Bytes
/0/1/9 : ""
/0/1/10 : 123
/0/1/11 : 1
/0/1/12 : 0
/0/1/15 : 3
Dec 21, 6:08:00.038 PM
receive error response
Receive REQUEST_ENTITY_INCOMPLETE(408)
Dec 21, 6:08:00.638 PM
send write
Send WRITE request on /1/0 using TLV(11542)
/1/0/0 : 123
/1/0/1 : 300
/1/0/2 : 1
/1/0/6 : true
/1/0/7 : "U"
Dec 21, 6:08:00.638 PM
receive success response
Receive CHANGED(204)

**Comment by jvermillard** [comment]
> the two blocks in CoAP packets didn't match for the token being different and so error 4.08 is returned.
It's a common mistake: two blocks should not share the same token; see:
https://github.com/eclipse-californium/californium/pull/2088
