### ISSUE TITLE
FW update test

### ISSUE THREAD

**Issue by mathns28** [eclipse-leshan/leshan#1603]
### Question

I'm new in lwm2m and I don't know  too much. Someone can help me?

 I'm trying to update a firmware from a client, but I don´t know how the server will works on it. 

Example, My server is running in a host as coap://localhost:5683, Is it possible to client request the file using coap://localhost:5683/firmwares/firmware.bin? And, How I will map it on server, recive the request, find the file on server and answer the client?
Is There a server demo to test the firmware update?

**Comment by sbernard31** [comment]
You should have a look at : https://github.com/eclipse-leshan/leshan/issues/70#issuecomment-2047006480

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by mathns28** [comment]
Yes, we can. 

Thanks for everything, again..
