### ISSUE TITLE
Removing presenceService.isClientAwake(destination) check

### ISSUE THREAD

**Issue by mattemyoo** [eclipse-leshan/leshan#1643]
### Question

Hello. Is there any risk of messing anything up if we were to disable for example these lines?:

https://github.com/eclipse-leshan/leshan/blob/583807b38d249350af3f390c219b4193cf770594/leshan-lwm2m-server/src/main/java/org/eclipse/leshan/server/queue/QueueModeLwM2mRequestSender.java#L65-L68

The reason is that we would like to still try to send a request to our device even though it is considered asleep.

**Comment by sbernard31** [comment]
> Is there any risk of messing anything up if we were to disable for example these lines?

I think it should be OK :thinking: 

> The reason is that we would like to still try to send a request to our device even though it is considered asleep.

Are you using the `PresenceService` or you don't use it at all ?

**Comment by sbernard31** [comment]
(let me know when we can close this issue)

**Comment by mattemyoo** [comment]
Yes we are using  `PresenceService`. It seems like 93s without a response, we the sleep event is triggered, right?


Anyway, you can close this issue now. We discovered the max timeout flag and did some more digging into the code.
