### ISSUE TITLE
Leshan does not decode SenML-CBOR string value (3) correctly

### ISSUE THREAD

**Issue by kipusoep** [eclipse-leshan/leshan#1654]
### Version(s)

f0825b5e92968a4022567214ad6b2a722d9cefa2

### Which components

leshan client demo

### What happened

I am trying to PUT SenML_CBOR data from my LWM2M server to the leshan client demo, but I get an error:
`Invalid SenML record : record must have a value (v,vb,vlo,vd,vs) : {"3": "hhh", "-2": "/3442/0/110"}`

This doesn't make sense to me, as the value (vs) is present in the form of `3`.
If I send the same payload in json format it works fine (with bn and vs obviously).
I checked the verbose logs and the client states:
`Unable to decode node[path:/3442/0/110] : 81a2613363686868622d326b2f333434322f302f313130`

If I take this binary hex and paste it in this [online cbor tool](https://cbor.me/), it also shows the correct json:
![image](https://github.com/user-attachments/assets/90ff7260-de38-4708-a3dc-1d633ffb5390)

Looking at [the source](https://github.com/eclipse-leshan/leshan/blob/2229014231ee2ae7117c9e69e77750b074d660f8/leshan-lwm2m-core/src/main/java/org/eclipse/leshan/senml/cbor/upokecenter/SenMLCborPackSerDes.java#L142) it tries to find an item with key `3`, but it is present...
So I am really confused about what's going on. If I do the same request from the leshan server demo, it works fine, but I'm not sure what the difference is?

Thanks in advance for any help!

### Relevant Output

This is the payload from the leshan server demo (left) vs my payload (right), maybe it's helpful?
![image](https://github.com/user-attachments/assets/f2ec54e2-2f4d-4736-b42a-8fe82a7d4505)

**Comment by sbernard31** [comment]
Thx for taking to report that.  :pray: 

I will try to have a look and will let you know what I will find.

**Comment by kipusoep** [comment]
@sbernard31 hi, thanks! But I think I might be doing something wrong, especially if you look at the payload comparison at the bottom of my post. Do you have any idea?
It seems the keys of the properties are different between them.

**Comment by sbernard31** [comment]
Ok so this is your payload : 

```
81a2613363686868622d326b2f333434322f302f313130

[{"3": "hhh", "-2": "/3442/0/110"}]

81                              # array(1)
   A2                           # map(2)
      61                        # text(1)
         33                     # "3"
      63                        # text(3)
         686868                 # "hhh"
      62                        # text(2)
         2D32                   # "-2"
      6B                        # text(11)
         2F333434322F302F313130 # "/3442/0/110"

===> Invalid SenML record : record must have a value (v,vb,vlo,vd,vs) : {"3": "hhh", "-2": "/3442/0/110"}
```

And this is the expected one : 
```
81A20363686868216B2F333434322F302F313130

[{3: "hhh", -2: "/3442/0/110"}]

81                              # array(1)
   A2                           # map(2)
      03                        # unsigned(3)
      63                        # text(3)
         686868                 # "hhh"
      21                        # negative(1)
      6B                        # text(11)
         2F333434322F302F313130 # "/3442/0/110"

==> LwM2mSingleResource [id=110, value=hhh, type=STRING]
```

The difference you are using string as key instead of number.
I will double check the RFC but I think Leshan is right.

I agree that error message is not so good.

**Comment by kipusoep** [comment]
It seems you are absolutely right! I tried using a different CBOR library (for C#) and used integer keys, now it works!

**Comment by sbernard31** [comment]
Reading [6.  CBOR Representation (application/senml+cbor)](https://datatracker.ietf.org/doc/html/rfc8428#section-6) : 

> For compactness, the CBOR representation uses integers for the
      labels, as defined in Table 4.  This table is conclusive, i.e.,
      there is no intention to define any additional integer map keys;
      any extensions will use string map keys.  This allows translators
      converting between CBOR and JSON representations to also convert
      all future labels without needing to update implementations.  Base
      values are given negative CBOR labels, and others are given
      non-negative labels.
      
 And examples confirm that.

**Comment by sbernard31** [comment]
Maybe something : 

>record must have a value : one of those field must be present v(number:2), vb(number:4), vlo(string:vlo) ,vd(number:8) or vs(number:3) 

?

**Comment by kipusoep** [comment]
Yeah I think it is an improvement, although I am afraid I still wouldn't figure it out if I has that error message instead :-P

**Comment by sbernard31** [comment]
> Yeah I think it is an improvement

Ok so I integrated that changed in `master` (commit a878c188c2c073319eebc36cfdda423a5e005518)

> although I am afraid I still wouldn't figure it out if I has that error message instead 

Arf at least it will be easier for Leshan devs to answer to this kind of question.  :grin: 


I think we can close this issue now.
