### ISSUE TITLE
Error when creating an unsuccessful ReadCompositeResponse

### ISSUE THREAD

**Issue by slaft** [eclipse-leshan/leshan#1674]
### Version(s)

2.0.0-M17

### Which components

server and client

### What happened

This exception is thrown when the client/server tries to create an unsuccessful ReadCompositeResponse:
`IllegalArgumentException content OR timestampedValue should be not null`

(Same for an ObserveCompositeResponse and CancelCompositeObservationResponse).

**Comment by sbernard31** [comment]
This should be fixed by : https://github.com/eclipse-leshan/leshan/pull/1676

Let me know if this is easier for you to test if I integrate it directly in `master` ?

**Comment by sbernard31** [comment]
Oops @JaroslawLegierski  I just see that you also work on it : https://github.com/JaroslawLegierski/leshan/commit/7803d95125bb16bdb7b5fb8fe36332eb7d664f23

We should improve communication, let me know when you work on something :slightly_smiling_face:

**Comment by slaft** [comment]
Yes that's ok, thanks

**Comment by slaft** [comment]
Sorry my answer wasn't clear at all 🙂, I meant that all the tests pass now.

**Comment by sbernard31** [comment]
Oh great thx :pray:

**Comment by JaroslawLegierski** [comment]
> Oops @JaroslawLegierski I just see that you also work on it : [JaroslawLegierski@7803d95](https://github.com/JaroslawLegierski/leshan/commit/7803d95125bb16bdb7b5fb8fe36332eb7d664f23)
> 
> We should improve communication, let me know when you work on something 🙂

Sure, I should have informed you earlier. I prepared only the first proposal on how we can solve this problem, but you were faster. 😅 Currently I'm working on #1504.
